# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_hash', models.CharField(blank=True, max_length=1000, null=True)),
                ('access_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('scope', models.CharField(blank=True, max_length=1000, null=True)),
                ('admin_storeuser_id', models.IntegerField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Store')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_id', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=1000, null=True)),
                ('storeusers', models.ManyToManyField(to='display.StoreUser')),
            ],
        ),
        migrations.AddField(
            model_name='storeuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.User'),
        ),
        migrations.AddField(
            model_name='store',
            name='storeusers',
            field=models.ManyToManyField(to='display.StoreUser'),
        ),
    ]
